nohup php over1.php > /tmp/o1.php &
nohup php over2.php > /tmp/o2.php &
nohup php over3.php > /tmp/o3.php &
nohup php over4.php > /tmp/o4.php &
nohup php over5.php > /tmp/o5.php &
nohup php over6.php > /tmp/o6.php &
nohup php over7.php > /tmp/o7.php &
nohup php over8.php > /tmp/o8.php &
nohup php over9.php > /tmp/o9.php &
nohup php over10.php > /tmp/o10.php &
nohup php over11.php > /tmp/o11.php &
nohup php over12.php > /tmp/o12.php &
nohup php over13.php > /tmp/o13.php &
nohup php over14.php > /tmp/o14.php &
nohup php over15.php > /tmp/o15.php &
nohup php over16.php > /tmp/o16.php &
nohup php over17.php > /tmp/o17.php &
nohup php over18.php > /tmp/o18.php &
nohup php over19.php > /tmp/o19.php &
nohup php over20.php > /tmp/o20.php &
