php ./cron.get.exceptions.php
php ./cron.get.exceptions.php
php ./cron.get.exceptions.php
php ./cron.get.exceptions.php
php ./cron.get.exceptions.php
php ./cron.get.exceptions.php
php ./cron.get.exceptions.php
php ./cron.get.exceptions.php
php ./cron.get.exceptions.php
php ./cron.get.exceptions.php
php ./cron.get.exceptions.php
