<?php

ini_set('display_errors',1);
ini_set('display_startup_errors',1);
ini_set('memory_limit',-1);
ini_set('max_execution_time', 900000);
header('Access-Control-Allow-Headers: Access-Control-Allow-Origin, Content-Type, Authorization');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET,PUT,POST,DELETE,PATCH,OPTIONS');
//header('Content-type: application/json');

require_once('class.XRDB.php');
$X=new XRDB();

//Legs
//Glutes
$post=array();
$post['table_name']="kss_bodypart";
$post['action']="insert";
$post['parent']=568;
$post['part_level']=2;
$post['bodypart_name']="Gulteus Maximus";
$post['display_order']=1;
$X->post($post);
$post=array();
$post['table_name']="kss_bodypart";
$post['action']="insert";
$post['parent']=568;
$post['part_level']=2;
$post['bodypart_name']="Gulteus Medius";
$post['display_order']=2;
$X->post($post);
$post=array();
$post['table_name']="kss_bodypart";
$post['action']="insert";
$post['parent']=568;
$post['part_level']=2;
$post['bodypart_name']="Gulteus Minimus";
$post['display_order']=3;
$X->post($post);
//Quads
$post=array();
$post['table_name']="kss_bodypart";
$post['action']="insert";
$post['parent']=569;
$post['part_level']=2;
$post['bodypart_name']="Rectus Formis";
$post['display_order']=1;
$X->post($post);
$post=array();
$post['table_name']="kss_bodypart";
$post['action']="insert";
$post['parent']=569;
$post['part_level']=2;
$post['bodypart_name']="Vastus Lateralis";
$post['display_order']=2;
$X->post($post);
$post=array();
$post['table_name']="kss_bodypart";
$post['action']="insert";
$post['parent']=569;
$post['part_level']=2;
$post['bodypart_name']="Vastus Intermedius";
$post['display_order']=3;
$X->post($post);
$post=array();
$post['table_name']="kss_bodypart";
$post['action']="insert";
$post['parent']=569;
$post['part_level']=2;
$post['bodypart_name']="Vastus Medialis";
$post['display_order']=4;
$X->post($post);
//Calves
$post=array();
$post['table_name']="kss_bodypart";
$post['action']="insert";
$post['parent']=571;
$post['part_level']=2;
$post['bodypart_name']="Gastrocnemius - Medial Head";
$post['display_order']=1;
$X->post($post);
$post=array();
$post['table_name']="kss_bodypart";
$post['action']="insert";
$post['parent']=571;
$post['part_level']=2;
$post['bodypart_name']="Gastrocnemius - Lateral Head";
$post['display_order']=2;
$X->post($post);
//Hamstrings
$post=array();
$post['table_name']="kss_bodypart";
$post['action']="insert";
$post['parent']=571;
$post['part_level']=2;
$post['bodypart_name']="Biceps Femoris";
$post['display_order']=1;
$X->post($post);
$post=array();
$post['table_name']="kss_bodypart";
$post['action']="insert";
$post['parent']=571;
$post['part_level']=2;
$post['bodypart_name']="Semitendinosus";
$post['display_order']=2;
$X->post($post);
$post=array();
$post['table_name']="kss_bodypart";
$post['action']="insert";
$post['parent']=571;
$post['part_level']=2;
$post['bodypart_name']="Semimembranosus";
$post['display_order']=3;
$X->post($post);
//Lats
$post=array();
$post['table_name']="kss_bodypart";
$post['action']="insert";
$post['parent']=572;
$post['part_level']=2;
$post['bodypart_name']="Latissimus Dorsi";
$post['display_order']=3;
$X->post($post);
