<?php

ini_set('display_errors',1);
ini_set('display_startup_errors',1);
ini_set('memory_limit',-1);
ini_set('max_execution_time', 900000);
header('Access-Control-Allow-Headers: Access-Control-Allow-Origin, Content-Type, Authorization');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET,PUT,POST,DELETE,PATCH,OPTIONS');
//header('Content-type: application/json');

require_once('class.XRDB.php');
$X=new XRDB();

//Legs
//Glutes
$post=array();
$post['table_name']="kss_dexa";
$post['action']="insert";
$post['user_id']=1;
$post['measured_date']="2022-04-30";
$post['measured_time']="1:10:05 PM";
$post['body_fat_pct']=21.4;
$post['total_mass']=194.8;
$post['total_mass_left']=96.9;
$post['total_mass_right']=97.9;
$post['fat_tissue']=41.6;
$post['lean_tissue']=146.9;
$post['BMC']=6.3;
$post['visceral_fat']=3.06;
$post['arms_lean_mass']=20.6;
$post['arms_total_mass']=25.5;
$post['arms_total_mass_left']=12.8;
$post['arms_total_mass_right']=12.8;
$post['arms_lean_mass_right']=10.3;
$post['arms_lean_mass_left']=10.3;
$post['arms_fat_mass']=4.0;
$post['arms_fat_mass_left']=2.0;
$post['arms_fat_mass_right']=2.0;
$post['arms_body_fat_pct']=15.9;
$post['arms_body_fat_pct_left']=15.9;
$post['arms_body_fat_pct_right']=15.9;
$post['arms_bmc']=1.0;
$post['arms_bmc_left']=0.5;
$post['arms_bmc_right']=0.5;
$post['legs_lean_mass']=45.5;
$post['legs_total_mass_left']=27.9;
$post['legs_total_mass_right']=29.5;
$post['legs_lean_mass_left']=22.1;
$post['legs_lean_mass_right']=23.4;
$post['legs_fat_mass']=9.5;
$post['legs_fat_mass_left']=4.6;
$post['legs_fat_mass_right']=4.9;
$post['legs_body_fat_pct']=16.6;
$post['legs_body_fat_pct_left']=16.5;
$post['legs_body_fat_pct_right']=16.6;
$post['legs_bmc']=57.4;
$post['leg_bmc_left']=27.9;
$post['legs_bmc_right']=29.5;
$post['trunk_lean_mass']=73.5;
$post['trunk_lean_mass_left']=36.6;
$post['trunk_lean_mass_right']=36.9;
$post['trunk_fat_mass']=26.0;
$post['trunk_fat_mass_left']=13.7;
$post['trunk_fat_mass_right']=12.3;
$post['trunk_body_fat_pct']=25.6;
$post['trunk_body_fat_pct_left']=26.7;
$post['trunk_body_fat_pct_right']=24.5;
$post['trunk_bmc']=101.5;
$post['trunk_bmc_left']=51.3;
$post['trunk_bmc_right']=50.2;
$post['trunk_total_mass_left']=51.3;
$post['trunk_total_mass_right']=50.2;
$post['android_lean_mass']=11.3;
$post['android_fat_mass']=4.8;
$post['android_body_fat_pct']=29.6;
$post['android_total_mass']=16.2;
$post['gynoid_total_mass']=27.2;
$post['gynoid_lean_mass']=21.8;
$post['gynoid_fat_mass']=4.8;
$post['gynoid_body_fat_pct']=17.5;
$post['total_lean_mass_left']=73.2;
$post['total_lean_mass_right']=73.7;
$post['bmd_head']=2.140;
$post['bmd_arms']=1.039;
$post['bmd_legs']=1.303;
$post['bmd_trunk']=0.969;
$post['bmd_ribs']=0.911;
$post['bmd_spine']=1.189;
$post['bmd_pelvis']=0.908;
$post['bmd_total']=1.200;
$X->post($post);

