<?php

ini_set('display_errors',1);
ini_set('display_startup_errors',1);
ini_set('memory_limit',-1);
ini_set('max_execution_time', 900000);
header('Access-Control-Allow-Headers: Access-Control-Allow-Origin, Content-Type, Authorization');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET,PUT,POST,DELETE,PATCH,OPTIONS');
//header('Content-type: application/json');

require_once('class.XRDB.php');
$X=new XRDB();

//Legs
//Glutes
$post=array();
$post['table_name']="kss_dexa";
$post['action']="insert";
$post['user_id']=1;
$post['measured_date']="2022-03-14";
$post['measured_time']="11:29:23 AM";
$post['body_fat_pct']=22.3;
$post['total_mass']=173.3;
$post['total_mass_left']=87.4;
$post['total_mass_right']=85.9;
$post['fat_tissue']=39.6;
$post['lean_tissue']=128.5;
$post['BMC']=6.3;
$post['visceral_fat']=2.48;
$post['arms_lean_mass']=16.6;
$post['arms_total_mass']=21.3;
$post['arms_total_mass_left']=10.9;
$post['arms_total_mass_right']=10.4;
$post['arms_lean_mass_right']=8.1; 
$post['arms_lean_mass_left']=8.6; 
$post['arms_fat_mass']=3.6;
$post['arms_fat_mass_left']=1.8;
$post['arms_fat_mass_right']=1.9;
$post['arms_body_fat_pct']=17.2;
$post['arms_body_fat_pct_left']=16.4;
$post['arms_body_fat_pct_right']=17.9;
$post['arms_bmc']=1.0;
$post['arms_bmc_left']=0.5;
$post['arms_bmc_right']=0.5;
$post['legs_lean_mass']=40.7;
$post['legs_total_mass_left']=26.2;
$post['legs_total_mass_right']=26.9;
$post['legs_lean_mass_left']=20.0;
$post['legs_lean_mass_right']=20.7;
$post['legs_fat_mass']=10.0;
$post['legs_fat_mass_left']=4.9;
$post['legs_fat_mass_right']=5.0;
$post['legs_body_fat_pct']=18.7;
$post['legs_body_fat_pct_left']=18.9;
$post['legs_body_fat_pct_right']=18.6;
$post['legs_bmc']=2.4;
$post['leg_bmc_left']=1.2;
$post['legs_bmc_right']=1.2;
$post['trunk_lean_mass']=63.9;
$post['trunk_lean_mass_left']=32.4;
$post['trunk_lean_mass_right']=31.5;
$post['trunk_fat_mass']=23.0;
$post['trunk_fat_mass_left']=12.0;
$post['trunk_fat_mass_right']=11.0;
$post['trunk_body_fat_pct']=25.9;
$post['trunk_body_fat_pct_left']=26.5;
$post['trunk_body_fat_pct_right']=25.3;
$post['trunk_bmc']=1.9;
$post['trunk_bmc_left']=0.9;
$post['trunk_bmc_right']=0.9;
$post['trunk_total_mass_left']=45.4;
$post['trunk_total_mass_right']=43.4;
$post['android_lean_mass']=10.1;
$post['android_fat_mass']=4.3;
$post['android_body_fat_pct']=29.4;
$post['android_total_mass']=14.5;
$post['gynoid_total_mass']=24.4;
$post['gynoid_lean_mass']=19.1;
$post['gynoid_fat_mass']=4.7;
$post['gynoid_body_fat_pct']=19.1;
$post['total_lean_mass_left']=64.6;
$post['total_lean_mass_right']=63.9;
$post['bmd_head']=2.166;
$post['bmd_arms']=1.093;
$post['bmd_legs']=1.268;
$post['bmd_trunk']=0.929;
$post['bmd_ribs']=0.833;
$post['bmd_spine']=1.150;
$post['bmd_pelvis']=0.900;
$post['bmd_total']=1.190;
$X->post($post);

