<?php

ini_set('display_errors',1);
ini_set('display_startup_errors',1);
ini_set('memory_limit',-1);
ini_set('max_execution_time', 900000);
header('Access-Control-Allow-Headers: Access-Control-Allow-Origin, Content-Type, Authorization');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET,PUT,POST,DELETE,PATCH,OPTIONS');
//header('Content-type: application/json');

require_once('class.XRDB.php');
$X=new XRDB();

//Legs
//Glutes
$post=array();
$post['table_name']="kss_dexa";
$post['action']="insert";
$post['user_id']=1;
$post['measured_date']="2022-06-29";
$post['measured_time']="10:53:25 AM";
$post['body_fat_pct']=18.3;
$post['total_mass']=192.0;
$post['total_mass_left']=95.9;
$post['total_mass_right']=96.2;
$post['fat_tissue']=31.5;
$post['lean_tissue']=150.5;
$post['BMC']=6.5;
$post['visceral_fat']=1.89;
$post['arms_lean_mass']=21.5;
$post['arms_total_mass']=25.8;
$post['arms_total_mass_left']=13.2;
$post['arms_total_mass_right']=12.7;
$post['arms_lean_mass_right']=10.4;
$post['arms_lean_mass_left']=11.0;
$post['arms_fat_mass']=3.4;
$post['arms_fat_mass_left']=1.7;
$post['arms_fat_mass_right']=1.7;
$post['arms_body_fat_pct']=13.2;
$post['arms_body_fat_pct_left']=12.6;
$post['arms_body_fat_pct_right']=13.8;
$post['arms_bmc']=1.0;
$post['arms_bmc_left']=0.5;
$post['arms_bmc_right']=0.5;
$post['legs_lean_mass']=47.7;
$post['legs_total_mass_left']=28.3;
$post['legs_total_mass_right']=30.1;
$post['legs_lean_mass_left']=23.3;
$post['legs_lean_mass_right']=24.4;
$post['legs_fat_mass']=8.5;
$post['legs_fat_mass_left']=3.9;
$post['legs_fat_mass_right']=4.5;
$post['legs_body_fat_pct']=14.5;
$post['legs_body_fat_pct_left']=13.8;
$post['legs_body_fat_pct_right']=15.1;
$post['legs_bmc']=58.5;
$post['leg_bmc_left']=28.3;
$post['legs_bmc_right']=30.1;
$post['trunk_lean_mass']=73.1;
$post['trunk_lean_mass_left']=36.2;
$post['trunk_lean_mass_right']=36.9;
$post['trunk_fat_mass']=21.1;
$post['trunk_fat_mass_left']=10.6;
$post['trunk_fat_mass_right']=10.4;
$post['trunk_body_fat_pct']=21.9;
$post['trunk_body_fat_pct_left']=22.2;
$post['trunk_body_fat_pct_right']=21.5;
$post['trunk_bmc']=96.3;
$post['trunk_bmc_left']=47.8;
$post['trunk_bmc_right']=48.4;
$post['trunk_total_mass_left']=47.8;
$post['trunk_total_mass_right']=48.4;
$post['android_lean_mass']=10.2;
$post['android_fat_mass']=3.4;
$post['android_body_fat_pct']=24.6;
$post['android_total_mass']=13.7;
$post['gynoid_total_mass']=26.5;
$post['gynoid_lean_mass']=21.9;
$post['gynoid_fat_mass']=4.0;
$post['gynoid_body_fat_pct']=14.9;
$post['total_lean_mass_left']=75.2;
$post['total_lean_mass_right']=75.3;
$post['bmd_head']=2.115;
$post['bmd_arms']=1.043;
$post['bmd_legs']=1.264;
$post['bmd_trunk']=0.965;
$post['bmd_ribs']=0.848;
$post['bmd_spine']=1.229;
$post['bmd_pelvis']=0.943;
$post['bmd_total']=1.186;
$X->post($post);

