<?php

ini_set('display_errors',1);
ini_set('display_startup_errors',1);
ini_set('memory_limit',-1);
ini_set('max_execution_time', 900000);
header('Access-Control-Allow-Headers: Access-Control-Allow-Origin, Content-Type, Authorization');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET,PUT,POST,DELETE,PATCH,OPTIONS');
//header('Content-type: application/json');

require_once('class.XRDB.php');
$X=new XRDB();

$post=array();
$post['table_name']="kss_user_week";
$post['action']="insert";
$post['user_id']=1;
$post['program_id']=558;
$post['user_program_id']=558;
$post['week_name']="Program 1 - Week 1";
$post['week_start_date']="2022-03-14";
$post['week_end_date']="2022-03-20";
$X->post($post);
$post=array();
$post['table_name']="kss_user_week";
$post['action']="insert";
$post['user_id']=1;
$post['program_id']=558;
$post['user_program_id']=558;
$post['week_name']="Program 1 - Week 2";
$post['week_count']=8;
$post['week_start_date']="2022-03-21";
$post['week_end_date']="2022-03-27";
$X->post($post);
$post=array();
$post['table_name']="kss_user_week";
$post['action']="insert";
$post['user_id']=1;
$post['program_id']=558;
$post['user_program_id']=558;
$post['week_name']="Program 1 - Week 3";
$post['week_start_date']="2022-03-28";
$post['week_end_date']="2022-04-03";
$X->post($post);
$post=array();
$post['table_name']="kss_user_week";
$post['action']="insert";
$post['user_id']=1;
$post['program_id']=558;
$post['user_program_id']=558;
$post['week_name']="Program 1 - Week 4";
$post['week_start_date']="2022-04-04";
$post['week_end_date']="2022-04-10";
$X->post($post);
$post=array();
$post['table_name']="kss_user_week";
$post['action']="insert";
$post['user_id']=1;
$post['program_id']=558;
$post['user_program_id']=558;
$post['week_name']="Program 1 - Week 5";
$post['week_start_date']="2022-04-11";
$post['week_end_date']="2022-04-17";
$X->post($post);
$post=array();
$post['table_name']="kss_user_week";
$post['action']="insert";
$post['user_id']=1;
$post['program_id']=558;
$post['user_program_id']=558;
$post['week_name']="Program 1 - Week 6";
$post['week_count']=8;
$post['week_start_date']="2022-04-18";
$post['week_end_date']="2022-04-24";
$X->post($post);
$post=array();
$post['table_name']="kss_user_week";
$post['action']="insert";
$post['user_id']=1;
$post['program_id']=558;
$post['user_program_id']=558;
$post['week_name']="Program 1 - Week 7";
$post['week_start_date']="2022-04-25";
$post['week_end_date']="2022-05-01";
$X->post($post);
$post=array();
$post['table_name']="kss_user_week";
$post['action']="insert";
$post['user_id']=1;
$post['program_id']=558;
$post['user_program_id']=558;
$post['week_name']="Program 1 - Week 8";
$post['week_start_date']="2022-05-02";
$post['week_end_date']="2022-05-08";
$X->post($post);

$post=array();
$post['table_name']="kss_user_week";
$post['action']="insert";
$post['user_id']=1;
$post['program_id']=558;
$post['user_program_id']=559;
$post['week_name']="Recomp Program - Week 1";
$post['week_start_date']="2022-05-22";
$post['week_end_date']="2022-06-02";
$X->post($post);

$post=array();
$post['table_name']="kss_user_week";
$post['action']="insert";
$post['user_id']=1;
$post['program_id']=558;
$post['user_program_id']=559;
$post['week_name']="Recomp Program - Week 2";
$post['week_start_date']="2022-06-03";
$post['week_end_date']="2022-06-09";
$X->post($post);
$post=array();
$post['table_name']="kss_user_week";
$post['action']="insert";
$post['user_id']=1;
$post['program_id']=558;
$post['user_program_id']=559;
$post['week_name']="Recomp Program - Week 3";
$post['week_start_date']="2022-06-10";
$post['week_end_date']="2022-06-16";
$X->post($post);
$post=array();
$post['table_name']="kss_user_week";
$post['action']="insert";
$post['user_id']=1;
$post['program_id']=558;
$post['user_program_id']=559;
$post['week_name']="Recomp Program - Week 4";
$post['week_start_date']="2022-06-17";
$post['week_end_date']="2022-06-23";
$X->post($post);
$post=array();
$post['table_name']="kss_user_week";
$post['action']="insert";
$post['user_id']=1;
$post['program_id']=558;
$post['user_program_id']=559;
$post['week_name']="Recomp Program - Week 5";
$post['week_start_date']="2022-06-24";
$post['week_end_date']="2022-06-29";
$X->post($post);
$post=array();
$post['table_name']="kss_user_week";
$post['action']="insert";
$post['user_id']=1;
$post['program_id']=558;
$post['user_program_id']=560;
$post['week_name']="Lean Mass Program - Week 1";
$post['week_start_date']="2022-06-30";
$post['week_end_date']="2022-07-06";
$X->post($post);
$post=array();
$post['table_name']="kss_user_week";
$post['action']="insert";
$post['user_id']=1;
$post['program_id']=558;
$post['user_program_id']=560;
$post['week_name']="Lean Mass Program - Week 2";
$post['week_start_date']="2022-07-07";
$post['week_end_date']="2022-07-13";
$X->post($post);
$post=array();
$post['table_name']="kss_user_week";
$post['action']="insert";
$post['user_id']=1;
$post['program_id']=558;
$post['user_program_id']=560;
$post['week_name']="Lean Mass Program - Week 3";
$post['week_start_date']="2022-07-07";
$post['week_end_date']="2022-07-13";
$X->post($post);
$post=array();
$post['table_name']="kss_user_week";
$post['action']="insert";
$post['user_id']=1;
$post['program_id']=558;
$post['user_program_id']=560;
$post['week_name']="Lean Mass Program - Week 4";
$post['week_start_date']="2022-07-14";
$post['week_end_date']="2022-07-20";
$X->post($post);
$post=array();
$post['table_name']="kss_user_week";
$post['action']="insert";
$post['user_id']=1;
$post['program_id']=558;
$post['user_program_id']=560;
$post['week_name']="Lean Mass Program - Week 5";
$post['week_start_date']="2022-07-21";
$post['week_end_date']="2022-07-27";
$X->post($post);
$post=array();
$post['table_name']="kss_user_week";
$post['action']="insert";
$post['user_id']=1;
$post['program_id']=558;
$post['user_program_id']=560;
$post['week_name']="Lean Mass Program - Week 6";
$post['week_start_date']="2022-07-28";
$post['week_end_date']="2022-08-03";
$X->post($post);
$post=array();
$post['table_name']="kss_user_week";
$post['action']="insert";
$post['user_id']=1;
$post['program_id']=558;
$post['user_program_id']=560;
$post['week_name']="Lean Mass Program - Week 7";
$post['week_start_date']="2022-08-04";
$post['week_end_date']="2022-08-10";
$X->post($post);
$post=array();
$post['table_name']="kss_user_week";
$post['action']="insert";
$post['user_id']=1;
$post['program_id']=558;
$post['user_program_id']=560;
$post['week_name']="Lean Mass Program - Week 8";
$post['week_start_date']="2022-08-11";
$post['week_end_date']="2022-08-17";
$X->post($post);
$post=array();
$post['table_name']="kss_user_week";
$post['action']="insert";
$post['user_id']=1;
$post['program_id']=558;
$post['user_program_id']=560;
$post['week_name']="Lean Mass Program - Week 8";
$post['week_start_date']="2022-08-18";
$post['week_end_date']="2022-08-24";
$X->post($post);
